In [2]:
import numpy as np

def input_matrix(rows, cols, name):
    print(f"Enter elements for {name} ({rows}x{cols}):")
    matrix = []
    for i in range(rows):
        row = list(map(float, input(f"Row {i+1}: ").split()))
        matrix.append(row)
    return np.array(matrix)

rows = int(input("Enter number of rows: "))
cols = int(input("Enter number of columns: "))

matrix1 = input_matrix(rows, cols, "Matrix 1")
matrix2 = input_matrix(rows, cols, "Matrix 2")

result = matrix1 + matrix2

print("Matrix 1:")
print(matrix1)
print("Matrix 2:")
print(matrix2)
print("Sum of Matrices:")
print(result)

Enter number of rows:  2
Enter number of columns:  2


Enter elements for Matrix 1 (2x2):


Row 1:  1 2
Row 2:  2 3


Enter elements for Matrix 2 (2x2):


Row 1:  3 4
Row 2:  4 5


Matrix 1:
[[1. 2.]
 [2. 3.]]
Matrix 2:
[[3. 4.]
 [4. 5.]]
Sum of Matrices:
[[4. 6.]
 [6. 8.]]
